Apartment_Management/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage,name='home'),
    path('about/', views.about,name='about'),
    path('', include('accounts.urls')),
    path('', include('complaints.urls')),
    path('', include('bookings.urls')),
    path('', include('buildings.urls')),
    path('', include('noticeboard.urls')),
    path('', include('visitors.urls')),

]


urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.http import HttpResponse
from django.shortcuts import render

app_name = 'accounts'


urlpatterns = [
    path('signup/', views.signup,name="signup"),
    path('login_user/', views.login_view , name='login_user'),
    path('logout_user/', views.logout_view , name='logout_user'),

    path('signup-watchmen/', views.signup_watchmen,name="signup_watchmen"),
    path('signup-Resident/',views.signup_resident,name="signup_resident"),
   
    path('edit-details/',views.edit_details,name="edit_details"),
    path('profile/',views.profile,name='profile'),
]

bookings/urls.py
from django.urls import path

from . import views
app_name = 'bookings'


urlpatterns = [
    path('bookings-list/', views.bookings_display_view.as_view(), name='bookings_display'),  
    path('bookings-create/', views.create_booking_view.as_view(), name='create_booking'),
    path('bookings-admin/', views.admin_bookings_view.as_view(), name='admin-booking'),
]


bookings/models.py
from django.db import models

from accounts.models import Resident
# Create your models here.
class Booking(models.Model) :
	WAITING = 'WAIT'
	ALLOTTED = 'ALOT'
	REJECTED = 'REJC'
	status_choices = [
		(WAITING, 'WAITING FOR APPROVAL'),
		(ALLOTTED, 'ALLOTTED'),
		(REJECTED, 'REJECTED'),
	]

	BADMINTON = 'BADM'
	TABLE_TENNIS = 'TATE'
	TENNIS = 'TENS'
	COMMUNITY_HALL = 'COMH'
	facility_choices = [
		(BADMINTON,'Badminton'),
		(TABLE_TENNIS, 'Table Tennis'),
		(TENNIS, 'Tennis'),
		(COMMUNITY_HALL, 'Community Hall'),
	]

	booking_id = models.AutoField(primary_key = True)
	user_id = models.ForeignKey(Resident,on_delete = models.CASCADE)
	facility = models.CharField(max_length = 20, choices = facility_choices)
	status = models.CharField(max_length = 4,choices = status_choices, default = WAITING)
	check_in = models.DateTimeField()
	duration = models.IntegerField()
	check_out = models.DateTimeField(null = True)

bookings/forms.py
from django import forms
from .models import Booking
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from bootstrap_datepicker_plus import DateTimePickerInput


class create_booking(forms.ModelForm):

    class Meta:
        model = Booking
        fields = ['facility','check_in','duration']
        widgets = {
        	'check_in' : DateTimePickerInput(),
        }

bookings/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django import forms
from django.views.generic.edit import FormView

from .models import Booking
from accounts.models import Resident
from .forms import create_booking

# Create your views here.
class bookings_display_view(generic.ListView) :
	model = Booking
	template_name = 'bookings/bookings_display.html'
	context_object_name = 'bookings_list'

	def get_queryset(self) :
		user_id = self.request.user.id
		return Booking.objects.filter(user_id__exact = user_id)

	def get_context_data(self, **kwargs):
	    context = super().get_context_data(**kwargs)
	    context['user_id'] = self.request.user.id
	    resident = Resident.objects.get(user_id__exact = self.request.user.id)
	    context['image_url'] = resident.image.url
	    return context

class create_booking_view(FormView) :
	model = Booking
	form_class = create_booking
	template_name = 'bookings/booking_create.html'
	
	def dispatch(self, request, *args, **kwargs) :
		self.success_url = reverse_lazy('bookings:bookings_display')
		return super().dispatch(request,args,kwargs)

	def get_context_data(self, **kwargs):
	    context = super().get_context_data(**kwargs)
	    context['booking_form'] = self.form_class
	    return context

	def form_valid(self, form) :
		booking = form.save(commit = False)
		booking.user_id = Resident.objects.get(user__exact = self.request.user)
		booking.save()
		return super().form_valid(form)

class admin_bookings_view(generic.ListView) :
	model = Booking
	template_name = 'bookings/bookings_admin.html'

	def get_context_data(self, **kwargs):
	    context = super().get_context_data(**kwargs)
	    context['user_id'] = self.request.user.id
	    image_url_list = []
	    full_name_list = []
	    bookings_list = self.model.objects.all() 
	    for c in bookings_list :
	    	resident = Resident.objects.get(user__exact = c.user_id)
	    	full_name = resident.user.first_name + " " + resident.user.last_name
	    	full_name_list.append(full_name)
	    	image_url_list.append(resident.image.url)
	    context['values'] = zip(full_name_list, image_url_list, bookings_list)
	    return context

	def post(self, request, **kwargs) :
		print("HELLLOOOO")
		if request.POST['status'] and request.POST['booking_id']:
			status = request.POST['status']
			booking_id = request.POST['booking_id']
			booking = Booking.objects.get(booking_id__exact = booking_id)
			booking.status = status
			booking.save()
		
		return HttpResponseRedirect(reverse_lazy('bookings:admin-booking'))

bookings/templates/bookings/booking_create.html
 <!-- file: polls/templates/polls/question_form.html -->
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   {% load bootstrap4 %}
   {% bootstrap_css %}
   {% bootstrap_javascript jquery='full' %}
   {{ form.media }}
 </head>
 <body>
 	<h1> New Booking </h1>
   <article class="media content-section">
   <div class="container">
     <div class="col-md-3">
       <form method="post">{% csrf_token %}
         {% bootstrap_form form %}
         {% buttons %}
         <button type="submit" class="btn btn-primary">Save</button>
         {% endbuttons %}
       </form>
     </div>
   </div>
    </article>
 </body>
 {% endblock %}

bookings/templates/bookings/bookings_admin.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <legend class = "border-bottom mb-4"><h2 class="text-center"><img  src="/static/booking.png" width = "45" height = "45" alt="home" /> <strong>Bookings</strong></h2></legend>
        {% for name, image_url, booking in values %}
        <article class="media content-section">
        <img class = "rounded-circle article-img"src = "{{ image_url }}">
        <div class="media-body">
          <div class="article-metadata">
            <medium class="text-muted"><b>Name</b> : {{ name }}</br></medium>
            <medium class="text-muted"><b>Booking-ID</b> : {{ booking.booking_id }}</br></medium>
            <medium class="text-muted"><b>Facility</b> : {{ booking.get_facility_display }}</br></medium>
            <medium class="text-muted"><b>Status</b> : {{ booking.get_status_display }}</br></medium>
            <medium class="text-muted"><b>Date & Time</b> : {{ booking.check_in }}</br></medium>
            <medium class="text-muted"><b>Duration</b> : {{ booking.duration }}</br></medium>
            {% if booking.status == 'WAIT'%}
              <form class="form-inline my-2 my-lg-3" method = "post" action="{% url 'bookings:admin-booking' %}">
                {% csrf_token %}
                <input type = "hidden" name = "booking_id" value = "{{ booking.booking_id }}">
                <button  class="btn btn-outline-success my-2 my-sm-0" type = "submit" name = "status" value = 'ALOT'>Approve
                </button>
                <button class="btn btn-outline-danger my-2 my-sm-0" type = "submit" name = "status" value = 'REJC'>Reject
                </button>
              </form>
            {% endif %}  
          </div>
        </div>
        </article>
      {% endfor %}
  </body>
</html>
{% endblock %}

bookings/templates/bookings/bookings_display.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
  <head>
  	<link rel="stylesheet" href="{% static 'admin-complaint.css' %}">	
    <meta charset="utf-8">
  </head>
  <body>
    <legend class = "border-bottom mb-4"><h2 class="text-center"><img  src="/static/booking.png" width = "45" height = "45" alt="home" /> <strong>Bookings</strong></h2></legend>
    <div  id = "create_booking button">
       <button class="btn btn-outline-success my-2 my-sm-0"><a href="{% url 'bookings:create_booking' %}">New Booking</a>
       </button>
    </div>
        {% for booking in bookings_list %}
        <article class="media content-section">
        <img class = "rounded-circle article-img"src = "{{ image_url }}">
        <div class="media-body">
          <div class="article-metadata">
            <medium class="text-muted"><b>Booking-ID</b> : {{ booking.booking_id }}</br></medium>
            <medium class="text-muted"><b>Facility</b> : {{ booking.get_facility_display }}</br></medium>
            <medium class="text-muted"><b>Status</b> : {{ booking.get_status_display }}</br></medium>
            <medium class="text-muted"><b>Check-in Time</b> : {{ booking.check_in }}</br></medium>
            <medium class="text-muted"><b>Duration</b> : {{ booking.duration }}</br></medium>
          </div>
        </div>
        </article>
      {% endfor %}
  </body>
</html>
{% endblock %}