Apartment_Management/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage,name='home'),
    path('about/', views.about,name='about'),
    path('', include('accounts.urls')),
    path('', include('complaints.urls')),
    path('', include('bookings.urls')),
    path('', include('buildings.urls')),
    path('', include('noticeboard.urls')),
    path('', include('visitors.urls')),

]


urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.http import HttpResponse
from django.shortcuts import render

app_name = 'accounts'


urlpatterns = [
    path('signup/', views.signup,name="signup"),
    path('login_user/', views.login_view , name='login_user'),
    path('logout_user/', views.logout_view , name='logout_user'),

    path('signup-watchmen/', views.signup_watchmen,name="signup_watchmen"),
    path('signup-Resident/',views.signup_resident,name="signup_resident"),
   
    path('edit-details/',views.edit_details,name="edit_details"),
    path('profile/',views.profile,name='profile'),
]

visitors/urls.py
from django.urls import path

from . import views
app_name = 'visitors'

urlpatterns = [
	path('visitors-display/', views.visitors_display_view.as_view(), name='visitors_display'),
	path('visitors-watchman/', views.watchman_visitor_view.as_view(), name='visitors_watchman'),
	path('visitors-entry/', views.visitor_entry_view.as_view(), name='visitors_entry'),
	path('resident-error/', views.resident_error_view, name='resident_error'),
]


visitors/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from accounts.models import Resident

# Create your models here.
class Visitor(models.Model) :
	WAITING = 'WAIT'
	APPROVED = 'APRV'
	REJECTED = 'REJC'
	status_choices = [
		(WAITING, 'WAITING FOR APPROVAL'),
		(APPROVED, 'APPROVED'),
		(REJECTED, 'REJECTED'),
	]
	visitor_id = models.AutoField(primary_key = True)
	user_id = models.ForeignKey(Resident,on_delete = models.CASCADE)
	fname = models.CharField(max_length = 20)
	lname = models.CharField(max_length = 20, null = True)
	status = models.CharField(max_length = 4,choices = status_choices, null = True)
	phone = PhoneNumberField(blank=True, help_text='Contact phone number')
	datetime_entry = models.DateTimeField(null = True)
	datetime_exit = models.DateTimeField(null = True)
	
	def __str__(self):
		return str(self.fname)

visitors/forms.py
from django import forms
from .models import Visitor
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from bootstrap_datepicker_plus import DateTimePickerInput
from searchableselect.widgets import SearchableSelect

class visitor_entry_form(forms.ModelForm):
	resident_name = forms.CharField(max_length = 20)
	
	def __init__(self, *args, **kwargs): 
	    super(forms.ModelForm, self).__init__(*args, **kwargs)
	    self.fields['fname'].label = 'First Name'
	    self.fields['lname'].label = 'Last Name'
	    self.fields['datetime_entry'].label = 'Entry Date & Time'


	class Meta :
		model = Visitor
		fields = ['fname','lname','phone','datetime_entry']
		widgets = {
			'resident_name' : SearchableSelect(model='User', search_field='first_name', limit=10),
			'datetime_entry' : DateTimePickerInput(),
		}
       

class visitor_exit_form(forms.ModelForm) :

	def __init__(self, *args, **kwargs): 
	    super(forms.ModelForm, self).__init__(*args, **kwargs)
	    self.fields['datetime_exit'].label = ''

	class Meta:
		model = Visitor
		fields = ['datetime_exit'] 
		widgets = {
			'datetime_exit' : DateTimePickerInput(),
		}

visitors/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django import forms
from django.views.generic.edit import FormView
from .models import Visitor
from .forms import visitor_exit_form, visitor_entry_form
from accounts.models import Resident
from django.contrib.auth.models import User

# Create your views here.
class visitors_display_view(generic.ListView) :
	model = Visitor
	template_name = 'visitors/visitors_display.html'
	context_object_name = 'visitors_list'

	def get_queryset(self) :
		user_id = self.request.user.id
		return Visitor.objects.filter(user_id__exact = user_id)

	def get_context_data(self, **kwargs):
	    context = super().get_context_data(**kwargs)
	    return context

	def post(self, request, **kwargs) :
		if request.POST['status'] and request.POST['visitor_id']:
			status = request.POST['status']
			visitor_id = request.POST['visitor_id']
			visitor = Visitor.objects.get(visitor_id__exact = visitor_id)
			visitor.status = status
			visitor.save()
		
		return HttpResponseRedirect(reverse_lazy('visitors:visitors_display'))

class watchman_visitor_view(FormView) :
	model = Visitor
	form_class = visitor_exit_form
	template_name = 'visitors/visitors_watchman.html'

	def dispatch(self, request, *args, **kwargs) :
		self.success_url = reverse_lazy('visitors:visitors_watchman')
		return super().dispatch(request,args,kwargs)

	def get_context_data(self, **kwargs):
	    context = super().get_context_data(**kwargs)
	    full_name_list = []
	    visitors_list = self.model.objects.all() 
	    for c in visitors_list :
	    	resident = Resident.objects.get(user__exact = c.user_id)
	    	full_name = resident.user.first_name + " " + resident.user.last_name
	    	full_name_list.append(full_name)
	    context['values'] = zip(full_name_list, visitors_list)
	    return context

	def form_valid(self, form) :
		visitor = form.save(commit = False)
		v = Visitor.objects.get(visitor_id__exact = self.request.POST['visitor_id'])
		v.datetime_exit = visitor.datetime_exit
		v.save()
		return super().form_valid(form)

class visitor_entry_view(FormView) :
	model = Visitor
	form_class = visitor_entry_form
	template_name = 'visitors/visitors_entry.html'

	def dispatch(self, request, *args, **kwargs) :
		self.success_url = reverse_lazy('visitors:visitors_watchman')
		return super().dispatch(request,args,kwargs)

	def get_context_data(self, **kwargs):
	    context = super().get_context_data(**kwargs)
	    return context

	def form_valid(self, form) :
		visitor = form.save(commit = False)
		try :
			r = Resident.objects.get(user_id__first_name__iexact = form.cleaned_data['resident_name'])
			visitor.user_id = r
			visitor.save()
		except :
			self.success_url = reverse_lazy('visitors:resident_error')
		return super().form_valid(form)

def resident_error_view(request) :
	return render(request,'visitors/resident_entry_error.html')

visitors/templates/visitors/resident_entry_error.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h5><strong>Sorry, the given resident doesn't exist in our database :(</strong></h5>
<a  href="{% url 'visitors:visitors_entry' %}"><button class="btn btn-outline-success my-2 my-sm-0">Try Again</button></a>
{% endblock %}

visitors/templates/visitors/visitors_display.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
  <head>
  	<link rel="stylesheet" href="{% static 'table.css' %}">	
    <meta charset="utf-8">
  </head>
  <body>

    <legend class = "border-bottom mb-4"><h2 class="text-center"><img  src="/static/visitor_disp.png" width = "45" height = "45" alt="home" /> <strong>Visitor's History</strong></h2></legend>
        {% if visitors_list %}
        {% for visitor in visitors_list %}
        <article class="media content-section">
        <img class = "rounded-circle article-img" src = "/static/visitor.png">
        <div class="media-body">
          <div class="article-metadata">
            <medium class="text-muted"><b>Visitor-ID</b> : {{ visitor.visitor_id }}</br></medium>
            <medium class="text-muted"><b>Name</b> : {{ visitor.fname }} {{visitor.lname }} </br></medium>
            {% if visitor.status %}
            <medium class="text-muted"><b>Status</b> : {{ visitor.get_status_display }}</br></medium>
            {% endif %}
            <medium class="text-muted"><b>Phone Number</b> : {{ visitor.phone }} </br></medium>
            <medium class="text-muted"><b>Date & Time of Entry</b> : {{ visitor.datetime_entry }}</br></medium>
            <medium class="text-muted"><b>Date & Time of Exit</b> : 
            {% if visitor.datetime_exit %}
            {{ visitor.datetime_exit }}
            {% else %}
            Visitor still inside, hasn't left
            {% endif %}
            </br></medium>
            {% if visitor.status == None %}
            <form class="form-inline my-2 my-lg-3" method = "post" action="{% url 'visitors:visitors_display' %}">
              {% csrf_token %}
              <input type = "hidden" name = "visitor_id" value = "{{ visitor.visitor_id }}">
              <button  class="btn btn-outline-success my-2 my-sm-0" type = "submit" name = "status" value = 'APRV'>Approve
              </button>
              <button class="btn btn-outline-success my-2 my-sm-0" type = "submit" name = "status" value = 'REJC'>Reject
              </button>
            </form>
            {% endif %}
          </div>
        </div>
        </article>
      {% endfor %}
      {% else %}
      <h3>There are no visitors :(</h3>
      {% endif %}
  </body>
</html>
{% endblock %}

visitors/templates/visitors/visitors_entry.html
 <!-- file: polls/templates/polls/question_form.html -->
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   {% load bootstrap4 %}
   {% bootstrap_css %}
   {% bootstrap_javascript jquery='full' %}
   {{ form.media }}
 </head>
 <body>
 	<h1 class="text-center"><strong>Visitor Entry</strong></h1>
   <article class="media content-section">
   <div class="container">
     <div class="col-md-3">
       <form method="post">{% csrf_token %}
         {% bootstrap_form form %}
         {% buttons %}
         <button type="submit" class="btn btn-primary">Save</button>
         {% endbuttons %}
       </form>
     </div>
   </div>
    </article>
 </body>
 {% endblock %}

visitors/templates/visitors/visitors_watchman.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <head>
    <link rel="stylesheet" href="{% static 'visitor-entry.css' %}">
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   {% load bootstrap4 %}
   {% bootstrap_css %}
   {% bootstrap_javascript jquery='full' %}
   {{ form.media }}
 </head>
 <body>
 	<legend class = "border-bottom mb-4"><h2 class="text-center"><img  src="/static/visitor_disp.png" width = "45" height = "45" alt="home" /> <strong>Vistor's List</strong></h2></legend>
  <div  id = "create_visitor_button">
     <a href="{% url 'visitors:visitors_entry' %}"><button class="btn btn-outline-success my-2 my-sm-0">New Visitor
     </button></a>
  </div>
  {% for full_name,visitor in values %}
   <article class="media content-section">
    <img class = "rounded-circle article-img" src = "/static/visitor.png">
    <div class="media-body">
      <div class="article-metadata">
        <medium class="text-muted"><b>Resident Name</b> : {{ full_name }}</br></medium>
        <medium class="text-muted"><b>Visitor-ID</b> : {{ visitor.visitor_id }}</br></medium>
        <medium class="text-muted"><b>Name</b> : {{ visitor.fname }} {{visitor.lname }} </br></medium>
        {% if visitor.status %}
        <medium class="text-muted"><b>Status</b> : {{ visitor.get_status_display }}</br></medium>
        {% endif %}
        <medium class="text-muted"><b>Phone Number</b> : {{ visitor.phone }} </br></medium>
        <medium class="text-muted"><b>Date & Time of Entry</b> : {{ visitor.datetime_entry }}</br></medium>
        <medium class="text-muted"><b>Date & Time of Exit</b> : 
        {% if visitor.datetime_exit %}
        {{ visitor.datetime_exit }}
        {% elif visitor.status == 'REJC' %}
        ---------------------------
        {% elif visitor.status == 'APRV' %}
        Visitor still inside, hasn't left
        <div class="container">
          <div class="col-md-3">
            <form method="post">{% csrf_token %}
              {% bootstrap_form form %}
              <input type = "hidden" name = "visitor_id" value = "{{ visitor.visitor_id }}">
              {% buttons %}
              <button type="submit" class="btn btn-primary">Save</button>
              {% endbuttons %}
            </form>
          </div>
        </div>
        {% endif %}
        </br></medium>
      </div>
    </div>
    </article>
    {% endfor %}
 </body>
 {% endblock %}