Apartment_Management/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage,name='home'),
    path('about/', views.about,name='about'),
    path('', include('accounts.urls')),
    path('', include('complaints.urls')),
    path('', include('bookings.urls')),
    path('', include('buildings.urls')),
    path('', include('noticeboard.urls')),
    path('', include('visitors.urls')),

]


urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.http import HttpResponse
from django.shortcuts import render

app_name = 'accounts'


urlpatterns = [
    path('signup/', views.signup,name="signup"),
    path('login_user/', views.login_view , name='login_user'),
    path('logout_user/', views.logout_view , name='logout_user'),

    path('signup-watchmen/', views.signup_watchmen,name="signup_watchmen"),
    path('signup-Resident/',views.signup_resident,name="signup_resident"),
   
    path('edit-details/',views.edit_details,name="edit_details"),
    path('profile/',views.profile,name='profile'),
]

complaints/urls.py
from django.urls import path

from . import views
app_name = 'complaints'


urlpatterns = [
    path('complaints-list/', views.complaints_display_view.as_view(), name='complaints_display'),
    path('complaints-lodge/', views.lodge_complaint_view.as_view(), name='lodge_complaint'),
    path('complaints-admin/', views.admin_complaint_view.as_view(), name='admin-complaint'),
]

complaints/models.py
from django.db import models
from accounts.models import Resident
# Create your models here.
class Complaints(models.Model) :
	#choice keys
	CREATED = 'CRE'
	IN_PROGRESS = 'PRG'
	COMPLETED = 'CMP'
	status_choices = [
		(CREATED, 'Created'),
		(IN_PROGRESS, 'In Progress'),
		(COMPLETED, 'Completed') 
	]
	complaint_id = models.AutoField(primary_key = True)
	user_id = models.ForeignKey(Resident,on_delete = models.CASCADE)
	status = models.CharField(max_length = 3,choices = status_choices, default = CREATED)
	content = models.TextField(max_length = 200)
	date = models.DateTimeField(auto_now_add = True)
	comments = models.TextField(max_length = 200)

	def __str__(self):
		return str(self.complaint_id)

complaints/forms.py
from django import forms
from .models import Complaints
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class lodge_complaint(forms.ModelForm):

    class Meta:
        model = Complaints
        fields = ['content']

complaints/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django import forms
from django.views.generic.edit import FormView

from accounts.models import Resident
from .models import Complaints
from .forms import lodge_complaint

# Create your views here.
class complaints_display_view(generic.ListView) :
	model = Complaints
	template_name = 'complaints/complaints_display.html'
	context_object_name = 'complaints_list'

	def get_queryset(self) :
		user_id = self.request.user.id
		return Complaints.objects.filter(user_id__exact = user_id)

	def get_context_data(self, **kwargs):
	    context = super().get_context_data(**kwargs)
	    context['user_id'] = self.request.user.id
	    resident = Resident.objects.get(user_id__exact = self.request.user.id)
	    context['image_url'] = resident.image.url
	    return context


class lodge_complaint_view(FormView) :
	model = Complaints
	form_class = lodge_complaint
	template_name = 'complaints/complaint_register.html'
	
	def dispatch(self, request, *args, **kwargs) :
		self.success_url = reverse_lazy('complaints:complaints_display')
		return super().dispatch(request,args,kwargs)

	def get_context_data(self, **kwargs):
	    context = super().get_context_data(**kwargs)
	    context['complaint_form'] = self.form_class
	    return context

	def form_valid(self, form) :
		complaint = form.save(commit = False)
		complaint.user_id = Resident.objects.get(user__exact = self.request.user)
		complaint.save()
		return super().form_valid(form)

class admin_complaint_view(generic.ListView) :
	model = Complaints
	template_name = 'complaints/complaints_admin.html'

	def get_context_data(self, **kwargs):
	    context = super().get_context_data(**kwargs)
	    context['user_id'] = self.request.user.id
	    image_url_list = []
	    full_name_list = []
	    complaints_list = self.model.objects.all() 
	    for c in complaints_list :
	    	resident = Resident.objects.get(user__exact = c.user_id)
	    	full_name = resident.user.first_name + " " + resident.user.last_name
	    	full_name_list.append(full_name)
	    	image_url_list.append(resident.image.url)
	    context['values'] = zip(full_name_list, image_url_list, complaints_list)
	    return context

	def post(self, request, **kwargs) :
		if request.POST['complaint_id'] :
			complaint_id = request.POST['complaint_id']
			complaint = Complaints.objects.get(complaint_id__exact = complaint_id)

		if request.POST['comments']:
			comments = request.POST['comments']
			complaint.comments = comments
		
		if request.POST['status'] != "" :
			status = request.POST['status']
			complaint.status = status	
		
		complaint.save()
		
		return HttpResponseRedirect(reverse_lazy('complaints:admin-complaint'))

complaints/templates/complaints/complaint_register.html
{% extends "base.html" %}
{%load crispy_forms_tags%}
{% block content %}
    <h1>Lodge a Complaint</h1>
    <form method = "POST" enctype = "multipart/form-data">
        {% csrf_token %}
        <fieldset class="form =-group">
          {{complaint_form|crispy}}
        </fieldset>
        <div class="form-group">
            <input type="submit">
    </form>
{% endblock content %}

complaints/templates/complaints/complaints_admin.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
  <head>
  	<link rel="stylesheet">	
    <meta charset="utf-8">
  </head>
  <body>
    <legend class = "border-bottom mb-4"><h2 class="text-center"><img  src="/static/complaint.png" width = "45" height = "45" alt="home" /> <strong>Registered Complaints</strong></h2></legend>
        {% for name, image_url, complaint in values %}
        <article class="media content-section">
        <img class = "rounded-circle article-img"src = "{{ image_url }}">
        <div class="media-body">
          <div class="article-metadata">
            <medium class="text-muted"><b>Name</b> : {{ name }}</br></medium>
            <medium class="text-muted"><b>Complaint-ID</b> : {{ complaint.complaint_id }}</br></medium>
            <medium class="text-muted"><b>Status</b> : {{ complaint.get_status_display }}</br></medium>
            <medium class="text-muted"><b>Date & Time</b> : {{ complaint.date }}</br></medium>
            <medium class="text-muted"><b>Content</b> : {{ complaint.content }}</br></medium>
            <medium class="text-muted"><b>Comments</b> : {{ complaint.comments }}</br></medium>
            <form class="form-inline my-2 my-lg-3" method = "post" action="{% url 'complaints:admin-complaint' %}">
              {% csrf_token %}
            <input type = "hidden" name = "status" value = "">
            <input type="radio" id="progress" name="status" value="PRG">
            <label for="progress"> In Progress </label><br>
            <input type="radio" id="completed" name="status" value="CMP">
            <label for="completed"> Completed  </label><br>
            
            <input class="form-control mr-sm-2" type="comments" placeholder="" aria-label="comments" name="comments">
            <input type = "hidden" name = "complaint_id" value = "{{ complaint.complaint_id }}">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Edit Comments</button>
            
        </form>
          </div>
        </div>
        </article>
      {% endfor %}
  </body>
</html>
{% endblock %}

complaints/templates/complaints/complaints_display.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
  <head>
  	<link rel="stylesheet" href="{% static 'table.css' %}">	
    <meta charset="utf-8">
  </head>
  <body>

    <legend class = "border-bottom mb-4"><h2 class="text-center"><img  src="/static/complaint.png" width = "45" height = "45" alt="home" /> <strong>Registered Complaints</strong></h2></legend>
    <div  id = "lodge_complaint_button">
       <button class="btn btn-outline-success my-2 my-sm-0"><a href="{% url 'complaints:lodge_complaint' %}">Lodge Complaint</a>
       </button>
    </div>
        {% for complaint in complaints_list %}
        <article class="media content-section">
        <img class = "rounded-circle article-img"src = "{{ image_url }}">
        <div class="media-body">
          <div class="article-metadata">
            <medium class="text-muted"><b>Complaint-ID</b> : {{ complaint.complaint_id }}</br></medium>
            <medium class="text-muted"><b>Status</b> : {{ complaint.get_status_display }}</br></medium>
            <medium class="text-muted"><b>Date & Time</b> : {{ complaint.date }}</br></medium>
            <medium class="text-muted"><b>Content</b> : {{ complaint.content }}</br></medium>
            <medium class="text-muted"><b>Comments</b> : {{ complaint.comments }}</br></medium>
          </div>
        </div>
        </article>
      {% endfor %}
  </body>
</html>
{% endblock %}