Apartment_Management/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage,name='home'),
    path('about/', views.about,name='about'),
    path('', include('accounts.urls')),
    path('', include('complaints.urls')),
    path('', include('bookings.urls')),
    path('', include('buildings.urls')),
    path('', include('noticeboard.urls')),
    path('', include('visitors.urls')),

]


urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.http import HttpResponse
from django.shortcuts import render

app_name = 'accounts'


urlpatterns = [
    path('signup/', views.signup,name="signup"),
    path('login_user/', views.login_view , name='login_user'),
    path('logout_user/', views.logout_view , name='logout_user'),

    path('signup-watchmen/', views.signup_watchmen,name="signup_watchmen"),
    path('signup-Resident/',views.signup_resident,name="signup_resident"),
   
    path('edit-details/',views.edit_details,name="edit_details"),
    path('profile/',views.profile,name='profile'),
]

bookings/urls.py
from django.urls import path

from . import views
app_name = 'bookings'


urlpatterns = [
    path('bookings-list/', views.bookings_display_view.as_view(), name='bookings_display'),  
    path('bookings-create/', views.create_booking_view.as_view(), name='create_booking'),
    path('bookings-admin/', views.admin_bookings_view.as_view(), name='admin-booking'),
]


buildings/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'buildings'

urlpatterns = [
	path('view/',views.view_main, name='main_view'),
   
	path('view/building/', views.view_building, name="building_details"),
	path('view/flat/',views.view_flat, name="flat_details"),
	path('view/service_directory/',views.view_service_directory, name="service_directory_details"),
	path('view/add_occupancy/',views.view_add_occupancy, name="add_occupancy"),
	path('view/view_occupancy/',views.view_occupancy, name="view_occupancy"),
	path('view/remove_occupancy/',views.remove_occupancy, name="remove_occupancy"),

]

complaints/urls.py
from django.urls import path

from . import views
app_name = 'complaints'


urlpatterns = [
    path('complaints-list/', views.complaints_display_view.as_view(), name='complaints_display'),
    path('complaints-lodge/', views.lodge_complaint_view.as_view(), name='lodge_complaint'),
    path('complaints-admin/', views.admin_complaint_view.as_view(), name='admin-complaint'),
]

visitors/urls.py
from django.urls import path

from . import views
app_name = 'visitors'

urlpatterns = [
	path('visitors-display/', views.visitors_display_view.as_view(), name='visitors_display'),
	path('visitors-watchman/', views.watchman_visitor_view.as_view(), name='visitors_watchman'),
	path('visitors-entry/', views.visitor_entry_view.as_view(), name='visitors_entry'),
	path('resident-error/', views.resident_error_view, name='resident_error'),
]


templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<html>
<style>
body { background-color: ##ffffff;
	    background-image: url(/static/about.jpeg);
	    height: 100%;
	    background-position: center;
	    background-repeat: no-repeat;
	    
	    color: #fff;
	 }
</style>
    <head>
        <meta charset="utf-8">
        <title>About</title>
    </head>
</html>
{% endblock %}

templates/base.html
{% load static %}
<html>
<head>
	<title>AMS</title>

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">

	<script type="text/javascript">
		var user = '{{request.user}}'
	</script>


</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container">

	  <a class="navbar-brand" href="{% url 'home' %}"><img  src="/static/apartments.png" width = "30" height = "30" alt="home" /></a>
	  <a class="navbar-brand" href="{% url 'home' %}">Home</a>

	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	    					<a class="nav-item nav-link" href="{% url 'noticeboard_notice_list' %}">NoticeBoard</a>
				{% if user.is_authenticated %}
						{% if user.is_superuser%}
							<a class="nav-item nav-link" href="{% url 'complaints:admin-complaint' %}">Complaints</a>
							<a class="nav-item nav-link" href="{% url 'bookings:admin-booking' %}">Bookings</a>
							<li class="nav-item dropdown">
							 <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								 Add User
							 </a>
							 <div class="dropdown-menu" aria-labelledby="navbarDropdown">
								 <a class="dropdown-item" href="{% url 'accounts:signup_resident' %}">Resident</a>
								 <div class="dropdown-divider"></div>
								 <a class="dropdown-item" href="{% url 'accounts:signup_watchmen' %}">Watchmen</a>
							 </div>
						 	</li>
						 	<a class="nav-item nav-link" href="{% url 'buildings:main_view'%}">View</a>



						{% elif user.profile.type == 'D' %}
						 	
							<a class="nav-item nav-link" href="{% url 'visitors:visitors_watchman' %}">Visitor Entry</a>


           				{% else %}
					 		 
					 		 <a class="nav-item nav-link" href="{% url 'complaints:complaints_display' %}">Complaints</a>
			 				 <a class="nav-item nav-link" href="{% url 'bookings:bookings_display' %}">Bookings</a>
			 				 <a class="nav-item nav-link" href="{% url 'visitors:visitors_display' %}">Visitors</a>
  		                     <a class="nav-item nav-link" href="{% url 'buildings:service_directory_details'%}">View Service Directory</a>
  		                     <a class="nav-item nav-link" href="{% url 'buildings:flat_details'%}">View Flats</a>
  		         
							 
					 {% endif %}
			 {% endif %}
			 <a class="nav-item nav-link" href="{% url 'about' %}">About</a>
			 


	    </ul>
			<div class="form-inline my-2 my-lg-0">

					{% if not user.is_authenticated %}
							<a href="{% url 'accounts:login_user' %}">
									<button class="btn btn-outline-success my-2 my-sm-0" type="button">Log In</button>
							</a>
							<!-- <a href="{% url 'accounts:signup_resident' %}">
									<button class="btn btn-outline-success my-2 my-sm-0 ml-2" type="button" >
											Sign Up
									</button>
							</a> -->
					{% else %}
					<div class="navbar-nav">

					
							{% if user.is_superuser  %}
											<a class="nav-item nav-link" href="#" >{{ user.username }}</a>
											<a href="{% url 'accounts:logout_user' %}">
													<button class="btn btn-outline-success my-2 my-sm-0" type="button">Logout</button>
											</a>
							{% else%}
								<a class="nav-item nav-link" href="{% url 'accounts:profile' %}" style="color: #32CD32">{{ user.username }}</a>
								<a href="{% url 'accounts:logout_user' %}">
									<button class="btn btn-outline-success my-2 my-sm-0" type="button">Logout</button>
								</a>
							
							{% endif %}
					</div>		

					{% endif %}



			</div>
		</div>
	</div>
</nav>
		<div class="container">

            <br>
            {% block content %}


            {% endblock content %}
         </div>


	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
<style>
.footer {
  position: fixed;
  left: 0;
  bottom: -10px;
  width: 100%;
  background-color: #343a40;
  color: white;
  text-align: center;
}
</style>

<div class="footer">
  <p>&copy; Copyright 2021 ApartWell.Inc</p>
</div>
</html>

templates/homepage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<html>
<style>
body { background-color: #0f121f;
	    background-image: url(/static/stars.png);
	    height: 100%;
	    background-position: center;
	    background-repeat: no-repeat;
	    background-size: cover;
	    color: #fff;
	 }
</style>
<head>
	<title>Homepage</title>

</head>

<body>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active" data-interval="5000">
      <img src="/static/AMS.png" class="d-block w-100" width="500" height="600" alt="...">
    </div>
    <div class="carousel-item" data-interval="5000">
      <img src="/static/appartments1.jpg" class="d-block w-100" width="500" height="600" alt="...">
    </div>
    <div class="carousel-item" data-interval="5000">
      <img src="/static/gym.jpg" class="d-block w-100" width="500" height="600" alt="...">
    </div>
    <div class="carousel-item" >
      <img src="/static/tree.jpg" class="d-block w-100" width="500" height="600" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>

<style>
.xyz {
  /*position: fixed;*/
  left: 0;
  bottom: 70px;
  width: 100%;
  color: white;
  text-align: center;
}
</style>
<div class="xyz">
<p style="font-size:5vw" class="text-center">Welcome to ApartWell!</p>
</div>

</body>
</html>
{% endblock %}